### ISSUE TITLE
Refuse traffic from abusive WP0 partners

### ISSUE THREAD

**Issue by zhuyifei1999** [Toollabs/video2commons#13]
[T129845: Commons and testwiki used as video hoster by Wikipedia Zero](https://phabricator.wikimedia.org/T129845)
Tool abused by [Hafizbd60883](https://commons.wikimedia.org/wiki/Special:Contributions/Hafizbd60883,) [Hasibhasan0918](https://commons.wikimedia.org/wiki/Special:Contributions/Hasibhasan0918)

**Comment by Steinsplitter** [comment]
When https://gerrit.wikimedia.org/r/#/c/280468/ is live on servers i will setup a filter for commons. The filter will likely tag tool uploads as well.

**Comment by zhuyifei1999** [comment]
Abuse Filter cannot detect OAuth tools, this tool need to detect the traffic itself.

**Comment by zhuyifei1999** [comment]
Per discussion with BBlack, this won't work.

**Comment by Steinsplitter** [comment]
Per my recent analysis: Most uploads are coming from payed lines.  So this won't work.
