### ISSUE TITLE
Errors on all recent YouTube uploads

### ISSUE THREAD

**Issue by owcz** [Toollabs/video2commons#16]
`	An exception occured: TaskError: /usr/bin/ffmpeg -y -i /srv/v2c/output/d0167752c939ebb5/dl.mp4 -threads 0 -skip_threshold 0 -bufsize 6000k -rc_init_occupancy 4000 -qmin 19 -qmax 19 -vcodec libvpx-vp9 -tile-columns 4 -f webm -ss 0 -aq 6 -ar 48000 -acodec libopus -pass 2 -passlogfile /srv/v2c/output/d0167752c939ebb5/dl.mp4.vp9.webm.log /srv/v2c/output/d0167752c939ebb5/dl.mp4.vp9.webm Exitcode: 1`

`An exception occured: TaskError: /usr/bin/ffmpeg -y -i /srv/v2c/output/637daf3ecef718b1/dl.mp4 -threads 0 -skip_threshold 0 -bufsize 6000k -rc_init_occupancy 4000 -qmin 19 -qmax 19 -vcodec libvpx-vp9 -tile-columns 4 -f webm -ss 0 -aq 6 -ar 48000 -acodec libopus -pass 2 -passlogfile /srv/v2c/output/637daf3ecef718b1/dl.mp4.vp9.webm.log /srv/v2c/output/637daf3ecef718b1/dl.mp4.vp9.webm Exitcode: 1`

`An exception occured: DownloadError: ERROR: content too short (expected 280259650 bytes and served 182450832)`

`An exception occured: DownloadError: ERROR: content too short (expected 280259650 bytes and served 182450832)`

**Comment by zhuyifei1999** [comment]
First two: #15, did you choose the experimental VP9/Opus encoding?
Last two: just some random download errors that a few restarts will fix it

**Comment by owcz** [comment]
Yes. Thanks

**Comment by zhuyifei1999** [comment]
Just leaving a note that I'm investigating on the chunk-too-small issue; it will be dealt on phab.
