### ISSUE TITLE
video2commons is not indexed in Hay’s Tools Directory

### ISSUE THREAD

**Issue by JeanFred** [Toollabs/video2commons#17]
Hello,

I noticed video2commons is not discoverable via [Hay’s Tools Directory](http://tools.wmflabs.org/hay/directory/), that I believe many users rely on to navigate the myriad of cool tools around :)

Is that something that the maintainers would be interested in? I’m happy to submit a PR for a toolinfo.json file if there is interest :)

**Comment by Steinsplitter** [comment]
Yes. Please.

**Comment by zhuyifei1999** [comment]
+1. Put it in www/static please.

**Comment by JeanFred** [comment]
There you go :)

**Comment by zhuyifei1999** [comment]
[Added to list](https://wikitech.wikimedia.org/w/index.php?title=User:Hay/directory&diff=449707&oldid=413003`).

**Comment by JeanFred** [comment]
Thanks for merging! Tool is now discoverable in the directory :) http://tools.wmflabs.org/hay/directory/#/search/video :)
