### ISSUE TITLE
Replace illegal characters

### ISSUE THREAD

**Issue by owcz** [Toollabs/video2commons#19]
Feature request: Replace illegal characters (e.g., replace a pipe with a hyphen) rather than forcing a manual rename. Most of the other Commons importers do this. Thanks for your continued support of this great tool

(Also a small typo in the error message: occured → occurred)

Example error:
`Error: An exception occured: AssertionError: Your filename contains an illegal character: |`

**Comment by zhuyifei1999** [comment]
Is there a common or standard replacement table, or can you point me to an open source comfirmed-to-replace tool so I can see how it replaces?

**Comment by owcz** [comment]
For instance, I believe the Commons Wizard replaces colons with hyphens. I think flickr2commons does the same? But it replaces the illegal characters automatically instead of prompting the user to change them manually

**Comment by zhuyifei1999** [comment]
Argh, they are both complicated tools that I have issues finding their replacement tables :/

**Comment by zhuyifei1999** [comment]
I'll ask MatmaRex regarding UW

**Comment by wilfredor** [comment]
I can't use a title on spanish, It could accept non english characters maybe UTF-8

**Comment by zhuyifei1999** [comment]
@wilfredor can you give me an example of a title that failed (with perfectly legal characters)?

**Comment by wilfredor** [comment]
For example, this video uploaded with video2commons tool https://commons.wikimedia.org/wiki/File:Asi_es_la_bandera_de_Venezuela.webm , spanish name should be "Así" and not "Asi"

**Comment by zhuyifei1999** [comment]
It's the period not the í triggered the illegal character logic.

**Comment by wilfredor** [comment]
Yes, illegal character was "." and not "í", thanks

**Comment by owcz** [comment]
@zhuyifei1999 What do you think about just replacing the illegal characters with spaces? (The uploader already handles the removal of multiple spaces.) It's be much better than dealing with the illegal characters manually and we can always switch to a better substitution table. A corollary could be to note just below the title field exactly which characters were replaced with spaces, so the user can edit as they please (though I doubt they will).

**Comment by zhuyifei1999** [comment]
MatmaRex found https://github.com/wikimedia/mediawiki/commit/cc8b00ed5bf69dafac2413d9c4387523a14bc62a, written by @Rillke
