### ISSUE TITLE
Design/usability suggestions

### ISSUE THREAD

**Issue by owcz** [Toollabs/video2commons#20]
A few usability suggestions (feel free to ignore):
- [x] Move "Add task..." to toolbar. After adding a video, the screen does not scroll, so the user has to scroll to the bottom of the screen to find the button. The top is a more logical place anyway.
- [x] Focus on URL field. After clicking "Add task..." the user is likely going to paste in their clipboard. Right now, I have to click in the URL field to focus before pasting. Ideally, the pop-up would auto-focus in that field, but an option to automatically or one-click paste the clipboard would be excellent.
- [x] Pressing "enter" in the URL field doesn't move to the next window as expected. "Enter" reloads the page.
- [ ] More than anything in the description field, I change the categories and sometimes the license, but I have to scroll through everything to get there. Maybe it's worth bouncing out that part to a second box? Or having a category lookup field, similar to Commons' Upload Wizard? (lower priority)
- [ ] Alternatively, (better?) the tool could reference a list on Commons so certain uploaders automatically get certain categories.
- [x] Stretch request: keyboard shortcut for "add task"
- [ ] Stretch request: batch upload (enter series of URLs, enter categories they have in common, upload the lot)

**Comment by zhuyifei1999** [comment]
1. Maybe I'll reverse the list as well?
2. +1
3. I'm aware of it but haven't investigated further.
4. Bouncing the part doesn't make sense and a category lookup field seems too complicated for this tool (might double the amount of Javascript loaded). I'd be happy if someone else implement that.
5. ? I don't get it.
6. Ctrl-N or something similar?
7. This requires quite a lot of change (mainly the web interface and API) on how this tool works currently.

**Comment by owcz** [comment]
(1) No prima facie objections to reversing the list

(5) The Flickr uploader [checks against a blacklist](https://commons.wikimedia.org/wiki/Commons:Questionable_Flickr_images) to reject uploads from certain users. (I think that would be smart for this too—though it isn't much of a problem yet—but...) If all uploads from a YouTube author X should have "Category:Videos by X", this could be a way of automating that. Lower priority.

(6) Ctrl-N would work for me (on Mac), as long as it doesn't conflict with browser shortcuts. [Here](https://en.wikipedia.org/wiki/Wikipedia:Keyboard_shortcuts) is the list of how Wikipedia does shortcuts, if it helps

**Comment by zhuyifei1999** [comment]
(2) done
(3) done
(6) done, it should have the same prefix as [MediaWiki access keys](https://en.wikipedia.org/wiki/Wikipedia:Keyboard_shortcuts) + N

**Comment by owcz** [comment]
Re: (3), hitting enter anywhere in the description box (even shift+enter) now goes to the next stage of the pop-up box rather than inserting a carriage return. I would think you want carriage returns to work normally within the description box but to advance the dialog everywhere else

**Comment by zhuyifei1999** [comment]
Done. Textareas are now excluded from auto submit on enter.

I'll work on the rest later when I have time and split the more difficult ones to more tasks.

**Comment by zhuyifei1999** [comment]
@owcz Can I edit the ticket description (your first comment) so it's easier to track status?

**Comment by zhuyifei1999** [comment]
Also, for 1, instead of moving buttons to the toolbar, how about scrolling to the bottom automatically after each submission? (`window.scrollTo(0,document.body.scrollHeight);`)

**Comment by owcz** [comment]
Of course—go for it. For (1), either would work—I would actually suggest both (Add button in toolbar, autoscroll for those who import a lot of videos), though I imagine the latter use case is not of the greatest concern.

**Comment by zhuyifei1999** [comment]
4 -> #49, 7 -> #48
