### ISSUE TITLE
Automatic license review: Flickr & Vimeo

### ISSUE THREAD

**Issue by owcz** [toollabs/video2commons#24]
I know it's baked into the YouTube API you're using, but is it possible to automatically pull the license info from Flickr and Vimeo as well? (I know there has to be some way to pull the Flickr data at least because the Flickr2commons tool does it.) The next step would be automatic license review, but I think that's a matter for the bots. This just would save uploaders the task of manually adding the license.

**Comment by zhuyifei1999** [comment]
Need youtube-dl support, will request in a few mins.

**Comment by zhuyifei1999** [comment]
Vimeo: rg3/youtube-dl#8726 (old ticket)

**Comment by zhuyifei1999** [comment]
The auto-adding-licence should be added, but auto licence review is unsecure and I'm not going to trust it in any way. AFAIK none of the OAuth tools do this.

**Comment by zhuyifei1999** [comment]
Not yet deployed & the vimeo part not yet done

**Comment by zhuyifei1999** [comment]
Deployed

**Comment by Steinsplitter** [comment]
automated license review isn't a good idea (abusefilter will block the uploads)

**Comment by legoktm** [comment]
Vimeo now has youtube-dl support: https://github.com/rg3/youtube-dl/commit/c38a67bcd5df639b9d7e7faa8685e76446803527

**Comment by zhuyifei1999** [comment]
Awesome! Thanks. I'll wait a few days so pip gets the new version.

**Comment by zhuyifei1999** [comment]
I just tested a few urls and it seems to be working.
