### ISSUE TITLE
YouTube import cuts off description

### ISSUE THREAD

**Issue by owcz** [Toollabs/video2commons#25]
The YouTube importer appears to have a character limit now on the description sections. Was this intentional? It's better to have the full video descriptions, in my experience.

**Comment by zhuyifei1999** [comment]
Do you have a test case for this?

**Comment by owcz** [comment]
It's happening on all YouTube links—every one I tried

**Comment by zhuyifei1999** [comment]
Just give me an example :)

**Comment by owcz** [comment]
* https://www.youtube.com/watch?v=_gi129oEk0M

converts to 
>|description={{en|1=This is Wikipedia. These servers give Wikipedia to the world. Nearly half a billion people use them every single month. Every kilowatt, hard drive and cable ...}}

(automatically shortened) instead of something like 
>|description={{en|1=This is Wikipedia. These servers give Wikipedia to the world. Nearly half a billion people use them every single month. Every kilowatt, hard drive and cable comes from your donation. Wikipedia is funded entirely by donations. Think about that for a second. That means these computers serve the common interest. Wikipedia circulates millions of pages of knowledge that anyone can add to in almost any language and it's all open-source. Wikipedia is free to read, to share, and to remix. After all, what else should we do with this awesome equipment? This is Wikipedia. #keepitfree https://donate.wikimedia.org

>Also view on Wikimedia Commons:
https://commons.wikimedia.org/wiki/File:This_is_Wikipedia.webm
and Vimeo:
https://vimeo.com/165495822
}}

**Comment by zhuyifei1999** [comment]
Upgraded youtube-dl to latest. Seems fixed

**Comment by zhuyifei1999** [comment]
For the record, this was rg3/youtube-dl#9415
