### ISSUE TITLE
Add ability to abort a task

### ISSUE THREAD

**Issue by zhuyifei1999** [Toollabs/video2commons#4]
May be very difficult currently. 
> Consumers (workers) should periodically check (and honor!) the is_aborted() method at controlled points in their task’s run() method. The more often, the better.

**Comment by Steinsplitter** [comment]
what about exec "job toolsname", then pars the jobid and exec "qdel jobid"?

**Comment by zhuyifei1999** [comment]
It's not running on grid engine, but on celery workers on [the video cluster](https://wikitech.wikimedia.org/wiki/Nova_Resource:Video/Help/video2commons#Backend).

**Comment by zhuyifei1999** [comment]
Not working as expected.

**Comment by zhuyifei1999** [comment]
Issues:
Aborting during first pass encoding are delayed.
Aborting during uploading simply won't work.
