### ISSUE TITLE
translatewiki.net scripts cannot push to master branch

### ISSUE THREAD

**Issue by siebrand** [Toollabs/video2commons#56]
The translatewiki.net integration currently fails with the following error:

    remote: error: GH006: Protected branch update failed for refs/heads/master.
    remote: error: Required status check "continuous-integration/travis-ci" is expected
    To git@github.com:Toollabs/video2commons.git
     ! [remote rejected] master -> master (protected branch hook declined)
    error: failed to push some refs to 'git@github.com:Toollabs/video2commons.git'

This should be resolved as soon as possible. I have disabled translatewiki.net integration until then.

Ping: @Nikerabbit

**Comment by zhuyifei1999** [comment]
Argh. I disabled that setting. Does it work now?

**Comment by zhuyifei1999** [comment]
Fixed per [T138498](https://phabricator.wikimedia.org/T138498)
