### ISSUE TITLE
Detect YouTube cc-by license

### ISSUE THREAD

**Issue by owcz** [Toollabs/video2commons#6]
Feature request

Great tool! When scraping YouTube video data, it would be nice to check whether a video is listed under a Creative Commons license (and then to auto-fill the license: `{{YouTube CC-BY}}`, ideally filled with the uploader's name (e.g., from the author field like `{{YouTube CC-BY|First Last}}`). The uploader attribution could also be linked to their YouTube channel (see ticket #7 )

**Comment by zhuyifei1999** [comment]
Will report the upstream bug when I got time. AFAIK youtube-dl gives neither the link to YouTube channel nor the video license.

**Comment by zhuyifei1999** [comment]
[Reported upstream](https://github.com/rg3/youtube-dl/issues/8712).

**Comment by owcz** [comment]
I see this is implemented now—nice! Thanks! If possible, it'd be great to have the author name specified in the template too (e.g., `{{YouTube CC-BY|The Laura Flanders Show}}`).

**Comment by zhuyifei1999** [comment]
Fixed in 176a57f (forgot to reference)
