### ISSUE TITLE
Short YouTube link error

### ISSUE THREAD

**Issue by VDK** [Toollabs/video2commons#65]
<code>
An exception occurred: TaskError: pywikibot.Error: APIError: spamblacklist: The text you wanted to save was blocked by the spam filter. This is probably caused by a link to a blacklisted external site. [help:See https://commons.wikimedia.org/w/api.php for API usage; invalidparameter:None; filekey:14cfbulw19qs.3jdg5a.1162075.webm; spamblacklist:{u'matches': [u'youtu.be/rKGNmhVmsEM']}; 0:[u'spamprotectiontext']; sessionkey:14cfbulw19qs.3jdg5a.1162075.webm; message:{u'params': u'youtu.be/rKGNmhVmsEM', u'key': u'spamprotectionmatch'}]</code>

What seems to be the problem here is that I put in the abbreviated URL to the YouTube video and the inclusion of this link in the file description page was flagged as spam 

It's fairly easy to expand an abbreviated YouTube URL, can this be implemented please?

**Comment by zhuyifei1999** [comment]
Indeed. I'm looking into it.

**Comment by zhuyifei1999** [comment]
Fixed in #66

**Comment by zhuyifei1999** [comment]
Actually, was it flagged as spam because it's included in the file description page or the upload summary?

**Comment by VDK** [comment]
I suspect the upload summary since the source info uses the YouTube link template

**Comment by zhuyifei1999** [comment]
ok I think #66 fixed it. Feel free to prove me wrong :)

**Comment by VDK** [comment]
I can confirm that things work correctly
