### ISSUE TITLE
Link author to YouTube uploader channel

### ISSUE THREAD

**Issue by owcz** [Toollabs/video2commons#7]
To preserve attribution, the author field should link directly to their YouTube channel, when available, i.e.,
```
|Author         = Bernie 2016 
```
to
```
|Author         = [https://www.youtube.com/channel/UCH1dpzjCEiGAt8CXkryhkZg Bernie 2016]
```

**Comment by zhuyifei1999** [comment]
[Reported upstream](https://github.com/rg3/youtube-dl/issues/8712).
