### ISSUE TITLE
Link to videoconvert

### ISSUE THREAD

**Issue by owcz** [toollabs/video2commons#71]
Went to upload a video from Dropbox and v2c wouldn't take the link. It would be helpful to offer some alternatives for when this happens. Primarily, I'd recommend linking to `toollabs:videoconvert` so that the uploader knows how else to upload the file.

I think it would be smart to link to videoconvert on the URL entry page anyway, in case someone has a video to upload and can't figure out where to put it. (I suppose even better would be direct upload!)

**Comment by zhuyifei1999** [comment]
I'm pretty sure the [link](https://github.com/toollabs/video2commons/blob/8a8317e1de66e6348a9b30bf40485e4c81741b97/video2commons/frontend/static/html/sourceForm.html#L21) [already](https://github.com/toollabs/video2commons/blob/8a8317e1de66e6348a9b30bf40485e4c81741b97/video2commons/frontend/static/video2commons.js#L420) [exists](https://github.com/toollabs/video2commons/blob/8a8317e1de66e6348a9b30bf40485e4c81741b97/video2commons/frontend/i18n/en.json#L39) in the source form.

Regarding supporting direct uploads, it's #42.

**Comment by owcz** [comment]
Ah, didn't even notice those were links. Might be worth underlining them in the CSS. For the link, I meant a link alongside "Error: Your url cannot be processed correctly", such as "Error: Your URL cannot be processed. Alternatively, consider uploading the file for conversion with the videoconvert tool." Just a thought

**Comment by zhuyifei1999** [comment]
Well, just like GitHub and MediaWiki, the link is underlined when it is hovered.

**Comment by zhuyifei1999** [comment]
Oh, and you can upload files now :)
