### ISSUE TITLE
Handle spamblacklist

### ISSUE THREAD

**Issue by owcz** [toollabs/video2commons#72]
`An exception occurred: TaskError: pywikibot.Error: APIError: spamblacklist: The text you wanted to save was blocked by the spam filter. This is probably caused by a link to a blacklisted external site. [filekey:....webm; message:{u'params': u'bit.ly/11jJQQT', u'key': u'spamprotectionmatch'}; sessionkey:....webm; help:See https://commons.wikimedia.org/w/api.php for API usage.; spamblacklist:{u'matches': [u'bit.ly/11jJQQT']}]` (Removed identifying info)

A friendlier error here would be to say that the bit.ly link needs to be removed, or else catch this in the license setup process before it goes to upload (otherwise have to re-customize info again).

**Comment by zhuyifei1999** [comment]
Pywikibot does not seem to have native support to [https://www.mediawiki.org/wiki/Extension:SpamBlacklist/API](Spamblacklist API). If the tool needs to call that API, I'll try to find the regexes in which the extension gets the list of urls and somehow make pywikibot call that API with the list.
