### ISSUE TITLE
YouTube author links use http:// not https://

### ISSUE THREAD

**Issue by legoktm** [toollabs/video2commons#80]
Example: https://commons.wikimedia.org/w/index.php?title=File:LCA_TV-_Lennart_Poettering.webm&action=edit&oldid=231391070

The link in the author field should use HTTPS

**Comment by zhuyifei1999** [comment]
Looking at [upstream code](https://github.com/rg3/youtube-dl/blob/e228616c6e73561f0c6d32d6b681bbba321c06aa/youtube_dl/extractor/youtube.py#L1458), and doing a test myself:
```
$ curl 'https://www.youtube.com/watch?v=LdRmnSHHVw4' --silent | grep '<link itemprop="url"'
              <link itemprop="url" href="https://www.youtube.com/watch?v=LdRmnSHHVw4">
          <link itemprop="url" href="http://www.youtube.com/user/linuxconfau2014">
          <link itemprop="url" href="https://plus.google.com/102248050178908953900">
      <link itemprop="url" href="https://i.ytimg.com/vi/LdRmnSHHVw4/hqdefault.jpg">
```

The best option would be to ask YouTube...

**Comment by zhuyifei1999** [comment]
I can hack around it, i.e. `if youtube: change to https`, but that's a hack.

**Comment by zhuyifei1999** [comment]
The patch is live; this should be fixed now

**Comment by legoktm** [comment]
Thanks!
