### ISSUE TITLE
Bookmarklet/URL parameter support

### ISSUE THREAD

**Issue by legoktm** [toollabs/video2commons#82]
Would it be possible to have something like <https://tools.wmflabs.org/video2commons/?upload=https://www.youtube.com/watch?v=2h7wR5ScQaM> automatically bring up the "Add task" form with the URL prefilled? I'm working on a tool that has a list of unimported youtube videos, so it would be more convenient, this feature could also be used to implement a bookmarklet.

**Comment by zhuyifei1999** [comment]
Hmm. Would it make sense to disable automatic initial loading of the task list when the parameter is provided?

**Comment by legoktm** [comment]
Possibly? I don't really have an opinion about that, just that once I finish adding the new video, it would be nice to see the full task list.

**Comment by zhuyifei1999** [comment]
{{done}}, the change is now live. https://tools.wmflabs.org/video2commons/#!https://www.youtube.com/watch?v=2h7wR5ScQaM works for me.
