### ISSUE TITLE
video2commons doesn't handle warnings (like the target filename being previously deleted) well

### ISSUE THREAD

**Issue by Poyekhali** [toollabs/video2commons#87]
While I am uploading a video of the Soviet anthem played in the 1981 October Revolution Parade, I encountered an exception, which is about a warning:

`An exception occurred: TaskError: pywikibot.Error: UploadWarning: was-deleted: The file USSR_Anthem,_Revolution_Day_1981_Гимн_СССР.webm was previously deleted.`

This means the filename which I picked for my upload was previously deleted. This warning is handled well in other upload tools like Special:Upload, but this is not the case for video2commons.

**Comment by zhuyifei1999** [comment]
This is basically #81
